#pragma once

#define TESTPLANT_CARD_ID -1
#define WATER_CARD_ID 0
#define MOLE_CARD_ID 1
#define FERTILIZER_CARD_ID 2
#define ANEMONE_FLOWER_CARD_ID 3
#define BLUE_JAZZ_CARD_ID 4
#define CROCUS_FLOWER_CARD_ID 5
#define TULIP_CARD_ID 6
#define RAIN_DAY 10

//----- Prices ------
#define TILE_COST 1000
#define WATER_COST 200
#define MOLE_COST 2000
#define FERTILIZER_COST 3000
#define ANEMONE_FLOWER_COST 1000
#define BLUE_JAZZ_COST 1000
#define CROCUS_FLOWER_COST 1000
#define TULIP_COST 1000

//-------
#define TIME_TIL_NEXT_TURN 1000f
